// CREATE A CLASS CALLED AS COMPUTER
// ASSIGN PROPERTIES AND DATA TYPES 
// CREATE CONSTRUCTOR AND A METHOD / FUNCTION CALLED AS PROCESS WHOSE RETURN TYPE IS STRING AND IT RETURNS A VALUE IN UPPER CASE
// CREATE ANOTHER OBJECT CALLED AS LAPTOP WHICH IS-A COMPUTER
// CREATE A THIRD OBJECT CALLED SERVER WHICH IS-A COMPUTER
// DECLARE DIFFERENT METHODS WITHIN LAPTOP AND SERVER CLASSES
// PRINT THE OUTPUT FROM LAPTOP AND SERVER CLASSES FOR PROCESS METHOD AND OTHER METHODS CREATED IN LAPTOP AND SERVER CLASSES