// CREATE A CLASS CALLED CAR
// CREATE DIFFERENT CARS WITH DIFFERENT CONFIGURATIONS LIKE MODEL, MAKE, COLOR, YEAR, AND PRICE
// ADD ALL CARS INTO OBJECT[]
// USE FOR OF LOOP AND FOREACH LOOP TO ITERATE AND PRINT THE VALUES